[workspace]
resolver = "3"
members = [
    "crates/common-structs",
    "crates/database",
    "crates/ytapi2",
    "crates/ytermusic",
]

[workspace.dependencies]
common-structs = { path = "crates/common-structs" }
ytapi2 = { path = "crates/ytapi2" }
database = { path = "crates/database" }
